name: Caller

env:
  TEST_VARIABLE: 42

on:
  push:
    branches:
      - main
      - called

jobs:
  some-job:
    uses: makar2/poc-github-actions-flows/.github/workflows/call-me.yml@main
    with:
      echo_me: hardcoded-value
