name: First

on:
  push:
    branches:
      - main
      - chain

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First commit started" && sleep 10 && echo "First commit ended"