name: My Precondition will fail

on:
  workflow_run:
    workflows: [Precondition]
    branches: [main, preconditioned]
    types:
      - completed

jobs:
  some-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat branch-name.txt